apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: apache
  name: apache-manager
rules:
- apiGroups: ["","apps","batch"]
  resources: ["pods","deployment","service"]
  verbs: ["get","watch","list","delete","create","patch"]
